### ISSUE TITLE
Error! Bad return status for module build on kernel: 6.1.19-v8+ (aarch64)

### ISSUE THREAD

**Issue by brandonrock919** [waveshare/WM8960-Audio-HAT#48]
I did 
git clone https://github.com/waveshare/WM8960-Audio-HAT
cd WM8960-Audio-HAT
sudo ./install.sh 
sudo reboot

but its not working 
this is the log

DKMS make.log for wm8960-soundcard-1.0 for kernel 6.1.19-v8+ (aarch64)
Mon 20 Mar 2023 01:33:32 PM EDT
make: Entering directory '/usr/src/linux-headers-6.1.19-v8+'
  CC [M]  /var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.o
  CC [M]  /var/lib/dkms/wm8960-soundcard/1.0/build/wm8960-soundcard.o
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c:1417:3: error: ‘const struct snd_soc_component_driver’ has no member named ‘non_legacy_dai_naming’; did you mean ‘legacy_dai_naming’?
 1417 |  .non_legacy_dai_naming = 1,
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   legacy_dai_naming
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c:1532:14: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1532 |  .remove =   wm8960_i2c_remove,
      |              ^~~~~~~~~~~~~~~~~
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c:1532:14: note: (near initialization for ‘wm8960_i2c_driver.remove’)
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c: In function ‘wm8960_hw_params’:
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c:882:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  882 |   if ((iface & 0x3) != 0) {
      |      ^
/var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.c:887:2: note: here
  887 |  default:
      |  ^~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/wm8960-soundcard/1.0/build/wm8960.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:2012: /var/lib/dkms/wm8960-soundcard/1.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.1.19-v8+'

**Comment by Stalker2408** [comment]
sorry for my Bad English

her my install steps to run WM8960 on kernel 6.1.21-V8+

sudo apt-get install raspberrypi-kernel-headers 
sudo apt-get dist-upgrade 
sudo apt-get update
git clone https://github.com/waveshare/WM8960-Audio-HAT
cd WM8960-Audio-HAT
sudo nano wm8960-soundcard.dts
Change target = <&i2c1>; to <&i2c0> ; ca. Zeile 25
sudo ./install.sh
sudo reboot

**Comment by YashasSingh** [comment]
hey I'm having the same issue and not sure what to do after doing the sudo nano command the &i2c1 is listed as &i2s nonetheless I changed it to &i2c0 but it still does not work for me

**Comment by alfyama** [comment]
@YashasSingh @Stalker2408 
Im facing the same issue, any updates?

**Comment by aschen-builder** [comment]
They are saying to change the [target value on line 25](https://github.com/waveshare/WM8960-Audio-HAT/blob/259d282dc4856318c6961e7d6a94b761308653d3/wm8960-soundcard.dts#L25) from `<&i2c1>` to `<&i2c0>`

**Comment by jvataman** [comment]
Confirming that the mentioned workaround works on pi zero 2W - 6.6.31+rpt-rpi-v8 aarch64
@Stalker2408 you are a life savior, danke ;)
